name: DrHunger
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  adobe_xd: ^1.0.0+1
  auto_animated: ^2.1.0
  bordered_text: ^1.0.0
  cloud_firestore: ^0.13.6
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  font_awesome_flutter: ^8.4.0
  google_fonts: ^0.3.5
  gradient_app_bar: ^0.1.3
  http: ^0.12.1
  pie_chart: ^3.1.1
  provider: ^4.1.2
  shared_preferences: ^0.5.7+3
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: assets/images/icon.png
  color: "ffffff"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    # #       - asset: fonts/Schyler-Italic.ttf
    # #         style: italic
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
  #         weight: 100
  #       - asset: assets/fonts/SF-Pro-Display-Thin.otf
  #         weight: 200
  #       - asset: assets/fonts/SF-Pro-Display-Light.otf
  #         weight: 300
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/SF-Pro-Display-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/SF-Pro-Display-Semibold.otf
  #         weight: 600
  #       - asset: assets/fonts/SF-Pro-Display-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/SF-Pro-Display-Heavy.otf
  #         weight: 800
  #       - asset: assets/fonts/SF-Pro-Display-Black.otf
  #         weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
